# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Resume
email: bastienbaranoff@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
      > this is a test of github pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bastienbaranoff.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bastienbaranoff
github_username: bbaranoff

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Specific to this theme
site_author: Bastien Baranoff
sticky_navigation: true
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
search_enabled: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
